// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_5WT70QyH3MsI87Isy7hlphJ3NkGj4SQ',
    appId: '1:213635375330:web:aef7d1971c184d52a53ebb',
    messagingSenderId: '213635375330',
    projectId: 'flutter-chat-app-18eb3',
    authDomain: 'flutter-chat-app-18eb3.firebaseapp.com',
    storageBucket: 'flutter-chat-app-18eb3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCgtewxAH1JV8VPOMk7YhcSMNXiH0fa4k',
    appId: '1:213635375330:android:18218656dba1fe8ba53ebb',
    messagingSenderId: '213635375330',
    projectId: 'flutter-chat-app-18eb3',
    storageBucket: 'flutter-chat-app-18eb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG7FItIh_lrvfCLNU3b5gtcUOe0ONSaO8',
    appId: '1:213635375330:ios:066bb4fa0a60c9f7a53ebb',
    messagingSenderId: '213635375330',
    projectId: 'flutter-chat-app-18eb3',
    storageBucket: 'flutter-chat-app-18eb3.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG7FItIh_lrvfCLNU3b5gtcUOe0ONSaO8',
    appId: '1:213635375330:ios:066bb4fa0a60c9f7a53ebb',
    messagingSenderId: '213635375330',
    projectId: 'flutter-chat-app-18eb3',
    storageBucket: 'flutter-chat-app-18eb3.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_5WT70QyH3MsI87Isy7hlphJ3NkGj4SQ',
    appId: '1:213635375330:web:45db7cb79d1b5c74a53ebb',
    messagingSenderId: '213635375330',
    projectId: 'flutter-chat-app-18eb3',
    authDomain: 'flutter-chat-app-18eb3.firebaseapp.com',
    storageBucket: 'flutter-chat-app-18eb3.firebasestorage.app',
  );
}
